name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.5-dind
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set dummy AWS credentials for DynamoDB Local
        run: |
          echo "AWS_ACCESS_KEY_ID=dummy" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS

      - name: Make setup script executable
        run: chmod +x setup-ci.sh create-dynamodb-tables.sh

      - name: Run setup script (docker-compose + DynamoDB tables)
        run: ./setup-ci.sh

      - name: Build and test with Gradle
        run: ./gradlew build test

      - name: Upload backend JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: build/quarkus-app/quarkus-run.jar

      - name: Upload Dockerfile artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-dockerfile
          path: Dockerfile
